storagecluster: Fix noobaa uninstall logs
openshift/ocs-operator pull request #1056
Opened 2021-02-11 07:21 UTC by iamniting

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

2021-02-15 14:10 UTC, raghavendra-talur requested changes

2021-02-15 14:10 UTC, raghavendra-talur commented on controllers/storagecluster/noobaa_system_reconciler.go
> +		r.Log.Info("Uninstall: NooBaa object", noobaa.ObjectMeta.Name, "found, but ownerReference not set to storagecluster. Skipping")
I suggest something like

```
r.Log.Info("Uninstall: NooBaa object found, but ownerReference not set to storagecluster. Skipping", "Object", noobaa.ObjectMeta.Name)
```

2021-02-16 13:35 UTC, raghavendra-talur approved these changes

2021-02-16 14:52 UTC, jarrpa approved these changes
/lgtm

2021-02-16 14:53 UTC, merged