Fix the OSD placement logic when arbiter is enabled
openshift/ocs-operator pull request #1092
Opened 2021-02-23 23:09 UTC by raghavendra-talur

2021-02-23 23:15 UTC, raghavendra-talur commented
cc: @iamniting

2021-02-24 04:05 UTC, jarrpa requested changes
Hmm... yes, I think this makes sense, though you have some unit test failures to address. Also, some of the test changes should be shuffled around. In particular, the addition of the new test cases (and their associated helper function) should be kept in their own commit at the end.

2021-02-24 04:05 UTC, jarrpa commented on controllers/storagecluster/cephcluster_test.go
> +			assert.Equal(t, fmt.Sprintf("%s-%d", deviceSet.Name, i), scds.Name, c.label)
Don't do the addition of labels in this PR... this is something that needs to be discussed further so we can unify on a common strategy for reporting unit tests.

2021-02-24 04:05 UTC, jarrpa commented on controllers/storagecluster/cephcluster_test.go
> +			} else if len(c.sc.Status.NodeTopologies.Labels[zoneTopologyLabel]) >= (deviceSet.Count / getReplicasPerFailureDomain(c.sc)) {
This change should be included in the same commit as the code changes, since it is technically required to allow the code commit to pass unit tests.

2021-02-24 06:24 UTC, raghavendra-talur commented
@jarrpa @obnoxxx @umangachapagain This is a fix that is required for arbiter placement. However, I see that the same bug exists in the non-arbiter mode too. To illustrate the same I have created #1093 .

If we want the behavior where `A replica count higher than 3 in a non-arbiter setup leads to a placement such that the distribution of the OSDs are equal across the failure domain(zones or racks)` then we can take this fix. However, it will be a change in the behavior compared to the previous builds.

2021-02-26 21:23 UTC, jarrpa approved these changes
/lgtm

2021-02-26 22:35 UTC, merged

2021-03-01 15:29 UTC, agarwal-mudit commented
@raghavendra-talur Please backport to 4.7

2021-03-01 18:02 UTC, raghavendra-talur commented
/cherrypick release-4.7