Set failure domain to host if flexibleScaling is enabled
openshift/ocs-operator pull request #1118
Opened 2021-03-17 07:41 UTC by nbalacha

Set the failure domain to true if flexible scaling is enabled
even if there are 3 or more zones.

Signed-off-by: N Balachandran <nibalach@redhat.com>

2021-03-17 07:58 UTC, umangachapagain requested changes
Commit message says "Set the failure domain to true", did you mean "host"?

2021-03-17 11:47 UTC, nbalacha commented
> Commit message says "Set the failure domain to true", did you mean "host"?

Done.

2021-03-18 15:43 UTC, umangachapagain commented
/approve
@jarrpa PTAL

2021-03-22 13:42 UTC, jarrpa approved these changes
/lgtm

2021-03-22 15:21 UTC, merged

2021-03-22 16:34 UTC, agarwal-mudit commented
/cherry-pick release-4.7