storagecluster: Increase mons db allocated space
openshift/ocs-operator pull request #1155
Opened 2021-04-19 14:08 UTC by iamniting

recent cases of mons db require more space then 10G. Increase the space
to 50G.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1944580

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

2021-04-19 21:25 UTC, obnoxxx commented
/test ocs-operator-ci

2021-04-19 21:34 UTC, obnoxxx approved these changes
this looks good in general.
But are we agreed on 50Gi?
The BZ seems to mention *at least* 50Gi ...

2021-04-20 16:08 UTC, jarrpa commented
> this looks good in general.
> But are we agreed on 50Gi?
> The BZ seems to mention _at least_ 50Gi ...

Yes, I believe so.

2021-04-20 16:09 UTC, jarrpa requested changes
The code change is simple enough and valid. However, I worry about merging this without any consideration for upgrade scenarios of existing clusters. I believe this should go in Rook, since it handles the creation of the storage volume. @travisn @leseb Thoughts?

2021-04-20 16:33 UTC, leseb commented
> The code change is simple enough and valid. However, I worry about merging this without any consideration for upgrade scenarios of existing clusters. I believe this should go in Rook, since it handles the creation of the storage volume. @travisn @leseb Thoughts?

Rook just creates the PVC based on what's provided by the template. If the CSI driver supports volume resize (block + fs) then we are covered. I don't think the mon store needs to be resized, but let me double check. If that's the case, an init container would do the trick!

2021-04-20 16:35 UTC, jarrpa commented
> Rook just creates the PVC based on what's provided by the template. If the CSI driver supports volume resize (block + fs) then we are covered. I don't think the mon store needs to be resized, but let me double check. If that's the case, an init container would do the trick!
> 
> Edit: nothing to resize on the mon data store if the fs is resized! Nothing to do on the Rook side.

So changing the CephCluster spec should lead to a modification of the Mon's PVC and thus trigger a volume expansion from the CSI driver?

2021-04-20 16:40 UTC, leseb commented
> > Rook just creates the PVC based on what's provided by the template. If the CSI driver supports volume resize (block + fs) then we are covered. I don't think the mon store needs to be resized, but let me double check. If that's the case, an init container would do the trick!
> > Edit: nothing to resize on the mon data store if the fs is resized! Nothing to do on the Rook side.
> 
> So changing the CephCluster spec should lead to a modification of the Mon's PVC and thus trigger a volume expansion from the CSI driver?

Correct.

2021-04-20 17:29 UTC, jarrpa approved these changes
Concerns have been addressed!

/lgtm

2021-04-20 19:36 UTC, merged