storagecluster: Add PriorityClasses support for all resources
openshift/ocs-operator pull request #1169
Opened 2021-04-27 06:46 UTC by iamniting

Add default PriorityClasses support

Use "systemNodeCritical" for the Mgr, Mon, Osd and
"openshiftUserCritical" for the Mds and rgw

Signed-off-by: Nitin Goyal nigoyal@redhat.com

pending from https://github.com/openshift/ocs-operator/pull/1166

look at rook PR: rook/rook#3206 for more details

2021-04-27 07:13 UTC, iamniting commented
@travisn Can you pls take a look?

2021-04-27 17:03 UTC, jarrpa requested changes
Code looks solid, but commit messages need tidying. Please use the phrasing "internal StorageClusters" and "external StorageCluster" in their respective commit messages.

2021-04-27 17:35 UTC, travisn commented
LGTM

2021-04-28 05:25 UTC, iamniting commented
> Code looks solid, but commit messages need tidying. Please use the phrasing "internal StorageClusters" and "external StorageCluster" in their respective commit messages.

Done

2021-04-28 05:26 UTC, iamniting commented
> LGTM

Thanks @travisn

2021-04-29 13:47 UTC, jarrpa approved these changes
/lgtm
/retest

2021-04-29 13:56 UTC, merged

2021-04-29 14:29 UTC, iamniting commented
/cherry-pick release-4.8