[WIP] pass monitoring labels to CephCluster and NooBaa
openshift/ocs-operator pull request #1176
Opened 2021-05-03 14:15 UTC by umangachapagain

+ monitoring labels from StorageCluster spec is passed on to
CephCluster spec so that Rook can take care of injecting these
labels into the monitoring resources that it creates.

+ [TODO] pass monitoring labels to NooBaa cluster

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

2021-06-14 05:36 UTC, umangachapagain commented
/retest

2021-06-21 14:29 UTC, umangachapagain commented
/retest

2021-06-21 19:22 UTC, jarrpa approved these changes
/lgtm

2021-06-21 23:33 UTC, jarrpa commented
/retest

2021-06-22 13:26 UTC, jarrpa commented
@umangachapagain Looks like the operator is crashing on nil pointer references. You need to check for `Spec.Monitoring != nil`.

2021-06-22 15:58 UTC, jarrpa commented
/hold

2021-06-23 19:28 UTC, jarrpa approved these changes
/lgtm
/hold cancel

2021-06-24 14:48 UTC, jarrpa requested changes
Looks like you missed another nil pointer reference. `Spec.Monitoring` is also a pointer: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ocs-operator/1176/pull-ci-openshift-ocs-operator-master-ocs-operator-bundle-e2e-aws/1408036391463424000/artifacts/ocs-operator-bundle-e2e-aws/ocs-must-gather/artifacts/ocs-must-gather/registry-build01-ci-openshift-org-ci-op-vivz3zrt-stable-sha256-67cd2177a98553b79315a9983bd2236fcbd9c6f51a55e0dc69a1c66bb44801ec/namespaces/openshift-storage/pods/ocs-operator-79d4f96699-hlq92/ocs-operator/ocs-operator/logs/current.log

/lgtm cancel

2021-06-28 13:27 UTC, umangachapagain commented
> Looks like you missed another nil pointer reference. `Spec.Monitoring` is also a pointer:...
> 
We have golang-ci lint for catching this. It's not doing the job :(

Added multiple nil checks. It shouldn't complain now.

2021-06-29 05:35 UTC, umangachapagain commented
/retest

2021-07-19 13:25 UTC, jarrpa approved these changes
/lgtm

2021-07-19 14:42 UTC, merged