must-gather: collect noobaa logs when external storage is enabled
openshift/ocs-operator pull request #1191
Opened 2021-05-26 12:04 UTC by rajatsing

Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

2021-05-26 12:38 UTC, crombus requested changes
We do not want to collect noobaa if stroage cluster is present.

You need different `if` section to do this with same condition storagecluster condition.

2021-05-27 09:32 UTC, rajatsing commented
> We do not want to collect noobaa if stroage cluster is present.
> 
> You need different `if` section to do this with same condition storagecluster condition.

Noo, I think we need noobaa collection when storagecluster is present as well as when external storagecluter is present.

2021-05-27 19:30 UTC, jarrpa commented
If I understand this correctly, the actual feature is to collect NooBaa information WITHOUT Ceph logs when you have an external StorageCluster, right? If so, a cleaner solution would be to introduce an `if !external` stanza in the existing `else` clause. I would imagine gathering NooBaa resources is independent of whether a StorageCluster exists or not, you should just be gathering any NooBaa resources that exist. This is especially important for our NooBaa-only deployments.

2021-05-31 08:07 UTC, crombus commented
my concern regarding the storagecluster was because in last release we had a bug that noobaa shouldn’t be collected if storagecluster not present. Now as we can have noobaa without storagecluster also. So @rajatsing now no checks needed just call the script as we call for ns and clusterdscope scripts and update the log line w.r.this.

2021-05-31 10:21 UTC, rajatsing commented
@crombus , I have made changes according to what you indicated. Now, noobaa is independent of storage and noobaa cluster

2021-05-31 11:02 UTC, crombus requested changes
code changes looks good. Just update the log msg.

2021-05-31 11:02 UTC, crombus commented on must-gather/collection-scripts/gather
>      echo "Collecting ceph and noobaa logs" | tee -a "${BASE_COLLECTION_PATH}"/gather-debug.log
remove noobaa

2021-05-31 11:41 UTC, rajatsing commented on must-gather/collection-scripts/gather
>      echo "Collecting ceph and noobaa logs" | tee -a "${BASE_COLLECTION_PATH}"/gather-debug.log
Thanks, doing right now.

2021-05-31 11:43 UTC, rajatsing commented on must-gather/collection-scripts/gather
>      echo "Collecting ceph and noobaa logs" | tee -a "${BASE_COLLECTION_PATH}"/gather-debug.log
done!.

2021-05-31 12:07 UTC, crombus approved these changes

2021-05-31 12:07 UTC, crombus commented
/test ocs-operator-ci

2021-05-31 12:18 UTC, crombus commented
/lgtm

2021-05-31 13:02 UTC, merged

2021-06-01 05:51 UTC, crombus commented
/cherry-pick release-4.8