Re-Change job template name to its original one,
openshift/ocs-operator pull request #1198
Opened 2021-06-01 19:41 UTC by pkesavap

Refer: https://bugzilla.redhat.com/show_bug.cgi?id=1966149

The osd removal job name on OCS4.7 and OCS4.8 is different.Thus this PR will set back the original name of the job

2021-06-02 13:13 UTC, agarwal-mudit commented
/ok-to-test

2021-06-03 07:20 UTC, pkesavap commented
/retest

2021-06-03 13:47 UTC, jarrpa requested changes
...is there any reason why you're making the names different now? I would just add `-job` to the end of both variables and leave the rest as-is. That said, it's kind of ridiculous to do `nameVar+"-job"` in the tests and not in the actual code. :) Please at least be consistent and do the same in the code.

2021-06-03 15:00 UTC, pkesavap commented
Hi @jarrpa 
In OCS 4.7, the template name and the job name were different, the job name had an extension of '-job' [template_name+'-job] appended to the template_name.

As part of [ https://bugzilla.redhat.com/show_bug.cgi?id=1966149], I wanted to be safe and give the template name and job name the same appellation it had in OCS 4.7, thus if the template name has 'ocs-extend-cluster' , then the job name should be 'ocs-extend-cluster-job' . 

Coming to the test cases, the reason why I gave the "-job" was that the method expects job name, and job name = template-name+"-job"

I implemented it this way, to have as minimal change possible along with keeping all the names similar to the one it had in OCS 4.7.

2021-06-03 18:10 UTC, pkesavap commented
@jarrpa As discussed offfline, i introduced the "-job" directly inside the job methods, 
with just this change, changes to the test file are also not needed.

2021-06-03 18:13 UTC, jarrpa approved these changes
/lgtm

2021-06-03 20:29 UTC, merged

2021-06-04 05:54 UTC, agarwal-mudit commented
/cherry-pick release-4.8

2021-06-04 06:05 UTC, pkesavap commented
/cherry-pick release-4.8

2021-06-04 06:07 UTC, agarwal-mudit commented
@pkesavap looks like this needs manual cherry picking as there are some conflicts.
Ping me if you need some help on gchat.

2021-06-04 06:18 UTC, agarwal-mudit commented
@pkesavap For release-4.8 you need to make same changes in `./controllers/storagecluster/reconcile.go`
because there is no file named ` controllers/storagecluster/job_templates.go ` in release-4.8