Refactored logs for storagecluster controller
openshift/ocs-operator pull request #1250
Opened 2021-07-01 12:32 UTC by priyanka19-98

Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

2021-07-01 12:32 UTC, priyanka19-98 commented
/cc @jarrpa

2021-07-01 13:02 UTC, umangachapagain requested changes

2021-07-01 13:02 UTC, umangachapagain commented on controllers/storagecluster/storageclasses.go
> +				return fmt.Errorf("Failed to restore StorageClass  %s because it is marked for deletion", existing.Name)
```suggestion
				return fmt.Errorf("failed to restore StorageClass  %s because it is marked for deletion", existing.Name)
```

2021-07-02 06:11 UTC, priyanka19-98 commented
/retest

2021-07-02 06:11 UTC, priyanka19-98 commented on controllers/storagecluster/cephblockpools.go
> +			r.Log.Error(err, "Unable to set Controller Refernce for CephBlockPool.", "CephBlockPool", klog.KRef(obj.Namespace, obj.Name))
done

2021-07-02 06:11 UTC, priyanka19-98 commented on controllers/storagecluster/cephblockpools.go
> +				return fmt.Errorf("Failed to restore initialization object %s because it is marked for deletion.", existing.Name)
done

2021-07-02 06:12 UTC, priyanka19-98 commented
made all the changes

2021-07-02 11:35 UTC, umangachapagain approved these changes
To be merged after #1248 since it brings the required modules.

2021-07-06 06:12 UTC, umangachapagain approved these changes
Thank You 🎆 

/lgtm

2021-07-06 07:33 UTC, merged