add ClusterResourceQuota alert
openshift/ocs-operator pull request #1311
Opened 2021-08-24 09:02 UTC by anmolsachan

Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

2021-08-24 10:35 UTC, anmolsachan commented
@umangachapagain @synarete Please review.

2021-08-25 12:35 UTC, umangachapagain requested changes

2021-08-25 12:35 UTC, umangachapagain commented on metrics/mixin/alerts/cluster-resource-quota.libsonnet
> +            alert: 'ClusterResourceQuotaNearLimit',
```suggestion
            alert: 'ODFClusterResourceQuotaNearLimit',
```

2021-08-30 08:29 UTC, agarwal-mudit commented
/lgtm

2021-08-30 10:29 UTC, merged