Obc quota alerts
openshift/ocs-operator pull request #1312
Opened 2021-08-24 13:45 UTC by anmolsachan

This PR adds Prometheus alerts to notify the users when the OBC usage goes beyond 80% of the limit(bytes/objects) set in the OBC definition.

Depends on: #1268 

Signed-off-by: Anmol Sachan anmol13694@gmail.com

2021-08-25 12:32 UTC, umangachapagain requested changes

2021-08-25 12:32 UTC, umangachapagain commented on metrics/mixin/alerts/obc.libsonnet
> +              message: 'OBC Quota used more than 80%.',
```suggestion
              message: 'OBC Quota(Bytes) used more than 80%.',
```

2021-08-25 12:32 UTC, umangachapagain commented on metrics/mixin/alerts/obc.libsonnet
> +              message: 'OBC Quota used more than 80%.',
```suggestion
              message: 'OBC Quota(Objects) used more than 80%.',
```

2021-08-30 09:13 UTC, umangachapagain commented
/unhold

2021-08-30 14:53 UTC, anmolsachan commented
@nbalacha @umangachapagain Thank you for the review. I have updated the PR. Please review.

2021-08-30 16:11 UTC, jarrpa approved these changes
Approving with @umangachapagain's blessing. :)

/lgtm

2021-08-30 16:24 UTC, merged