ocs-to-ocs: fix all the panic
openshift/ocs-operator pull request #1659
Opened 2022-05-10 13:48 UTC by subhamkrai

fixing all the panic nil pointer error

Signed-off-by: subhamkrai <srai@redhat.com>

2022-05-10 14:57 UTC, subhamkrai commented
PTAL @nb-ohad  @Madhu-1 @umangachapagain @iamniting @rexagod

2022-05-10 15:12 UTC, nb-ohad requested changes

2022-05-10 15:12 UTC, nb-ohad commented on controllers/storageclassclaim/storageclassclaim_controller.go
>  		r.cephBlockPool.Labels[controllers.StorageConsumerNameLabel] = r.storageConsumer.Name
```suggestion
		r.cephBlockPool.Labels = map[string]string {
			controllers.StorageConsumerNameLabel: r.storageConsumer.Name,
		}
```

2022-05-10 15:12 UTC, nb-ohad commented on controllers/storageclassclaim/storageclassclaim_controller.go
> +
```suggestion
	r.cephResourcesByName = map[string]*v1alpha1.CephResourcesSpec{}
```

2022-05-10 15:12 UTC, nb-ohad commented on controllers/storageclassclaim/storageclassclaim_controller.go
> +			r.storageConsumer.Namespace = r.storageClassClaim.Namespace
Don't assume same namespace for Claim (user accesiable API)  and consumer (internal API), use storage clsuter instead (which is already loaded):
```suggestion
			r.storageConsumer = &v1alpha1.StorageConsumer{}
			r.storageConsumer.Name = ownerRefs[i].Name
			r.storageConsumer.Namespace = r.storageCluster.Namespace
```

2022-05-10 15:12 UTC, nb-ohad commented on controllers/storageclassclaim/storageclassclaim_controller.go
> +	r.storageConsumer = &v1alpha1.StorageConsumer{}
Please create the object only if you found an owner ref
```suggestion
```

2022-05-10 17:44 UTC, merged

2022-05-11 09:51 UTC, agarwal-mudit commented
/cherry-pick release-4.11