Update script to specific noobaa version and add security for catalog source
openshift/ocs-operator pull request #1890
Opened 2022-11-23 15:03 UTC by subhamkrai

Update script to specific noobaa version instead of master.

Add security context for catalog source until we upgrade opm to file-based catalog

2022-11-23 15:05 UTC, subhamkrai commented
/assign @iamniting

2022-11-23 15:30 UTC, iamniting requested changes

2022-11-23 15:30 UTC, iamniting commented on deploy/deploy-with-olm.yaml
> +    - openshift-storage
Can you remove this change?

2022-11-29 10:10 UTC, iamniting commented
Hey @subhamkrai The ocs-operator-ci is failing can you pls check?

2023-01-12 06:22 UTC, subhamkrai commented
> Hey @subhamkrai The ocs-operator-ci is failing can you pls check?

@iamniting running `make gen-latest-deploy-yaml` removing changes in `deploy-with-olm.yaml` any idea how I can keep the changes?

2023-01-12 11:56 UTC, iamniting commented
> > Hey @subhamkrai The ocs-operator-ci is failing can you pls check?
> 
> @iamniting running `make gen-latest-deploy-yaml` removing changes in `deploy-with-olm.yaml` any idea how I can keep the changes?

After digging it a bit it looks like you are required to change the spec here <https://github.com/red-hat-storage/ocs-operator/blob/main/pkg/deploy-manager/subscription.go#L130>

2023-01-12 12:29 UTC, iamniting approved these changes
/lgtm

2023-01-12 13:41 UTC, merged