Fix 'make gen-latest-csv' failure
openshift/ocs-operator pull request #751
Opened 2020-09-04 13:07 UTC by aruniiird

'make gen-latest-csv' command fails when 'deploy/bundlemanifests/'
directory dont have any 'yaml' files in it. This is a fix for it.

Fix Issue: https://github.com/openshift/ocs-operator/issues/750

Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

2020-09-04 14:57 UTC, jarrpa commented
...this doesn't seem right. Why would we build the CSV with no role manifests?

2020-09-04 15:00 UTC, jarrpa commented
I am noticing that you did not commit the `deploy/csv-template` changes in your previous PR. Can you add those?

2020-09-07 07:06 UTC, bipuladh commented
I did in the commit mentioned above. However, after pulling 1c30d14be it seems to be working but two files named `dummy.yaml`  are getting created on their own. (Can be seen in https://github.com/openshift/ocs-operator/pull/754)

2020-09-21 20:03 UTC, jarrpa requested changes
There has been no follow up on #750, so I can't accept this as a valid PR. It also still strikes me as wrong that we would even need to do this.

2020-09-23 08:03 UTC, aruniiird commented
> There has been no follow up on #750, so I can't accept this as a valid PR. It also still strikes me as wrong that we would even need to do this.

@jarrpa , the line we have changed here is a `copy` statement (which is for taking backup) and the script was failing, without any error message, as there were no files in it. Even though this may be a rare occurrence, IMHO, we should not be failing at a point which could be avoided.

2020-11-05 10:06 UTC, nbalacha commented
There is a different PR up for this same problem at https://github.com/openshift/ocs-operator/pull/891

2020-11-05 11:11 UTC, closed without merging