README.md fixes
openshift/ocs-operator pull request #776
Opened 2020-09-22 16:14 UTC by renan-campos

I followed the instructions on the README.md to deploy a custom ocs-operator and noted two parts that weren't consistent with the documentation. Specifying the target namespace for the catalogSource is important because the deployment will fail otherwise.

2020-11-02 23:39 UTC, obnoxxx commented
@renan-campos - thanks! This looks reasonable.
Please do rebase on top of current master to get rid of those merge conflicts.

2020-11-02 23:41 UTC, jarrpa requested changes
So sorry I missed this!! I love seeing PRs like this, so the change is welcome.

The changes look good, but the commits need some cleanup. Please rebase to remove the merge conflicts and trim down the commits to only the two relevant ones, no merge commits.

2020-11-09 19:10 UTC, jarrpa approved these changes

2020-11-10 04:08 UTC, umangachapagain approved these changes
/lgtm

2020-11-10 06:36 UTC, umangachapagain commented
/override ci/prow/ocs-operator-bundle-e2e-aws 
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws

2020-11-10 06:38 UTC, merged