Refactor: Helper function to eliminate duplicate code.
openshift/ocs-operator pull request #804
Opened 2020-10-05 09:46 UTC by rajatsing

Added helper functions to remove code duplicate code.

Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

2020-10-05 19:18 UTC, jarrpa requested changes
Looks handy! The function names could use some work. Also, try and avoid generic commit descriptions. Try something like "refactor: helper functions to generate placement structs"

2020-10-05 19:18 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +func setWeightedPodAffinityTerm(selector string) []corev1.WeightedPodAffinityTerm {
```suggestion
func getWeightedPodAffinityTerm(selector string) []corev1.WeightedPodAffinityTerm {
```

2020-10-05 19:18 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +func setPodAffinityTerm(selector string) []corev1.PodAffinityTerm {
```suggestion
func getPodAffinityTerm(selector string) []corev1.PodAffinityTerm {
```

2020-10-05 19:18 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +func setToleration() []corev1.Toleration {
```suggestion
func getOcsToleration() []corev1.Toleration {
```

2020-10-05 19:18 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +func setNodeSelector() *corev1.NodeSelector {
```suggestion
func getOcsNodeSelector() *corev1.NodeSelector {
```

2020-10-06 08:45 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +func setWeightedPodAffinityTerm(selector string) []corev1.WeightedPodAffinityTerm {
Done!

2020-10-06 08:45 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +func setPodAffinityTerm(selector string) []corev1.PodAffinityTerm {
Done

2020-10-06 08:45 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +func setToleration() []corev1.Toleration {
Done

2020-10-06 08:45 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +func setNodeSelector() *corev1.NodeSelector {
Done

2020-10-07 07:45 UTC, umangachapagain requested changes
I don't see any value add to this.

I prefer duplicate code (for something as static as this) rather than a bunch of function calls.
We could just define global vars/constants and re-use it (if duplication is a concern)? Saves a lot of calls.

Unless I'm completely missing the point, I don't agree with this refactor as it is.

2020-10-07 08:02 UTC, rajatsing commented
@umangachapagain  above is [disscussed here](https://github.com/openshift/ocs-operator/pull/727/files#r485077430) and [here](https://github.com/openshift/ocs-operator/pull/727/files#r485076961)

2020-10-07 13:13 UTC, jarrpa commented
Why is reducing duplication not inherently valuable? I believe we've already run into scenarios where we forgot to update some components when we decided to implement a change that was supposed to affect all components.

The functions also allow us to generate structs that are largely identical save for one field. If  we did it with vars/consts we'd have large structs that were largely the same. Again, why is this not valuable?

2020-10-09 09:12 UTC, rajatsing commented
@umangachapagain do you have any reviews in it , otherwise @jarrpa  can go ahead and merge this!

2020-10-09 10:51 UTC, umangachapagain commented
> Why is reducing duplication not inherently valuable?

It's never inherently valuable. Even if it is, it's negligible in this case.

> I believe we've already run into scenarios where we forgot to update some components when we decided to implement a change that was supposed to affect all components.

I don't see this re-factor helping us fix those issues. Even with this re-factor one can mess it up (vs the variables which was pretty obvious).

What about when we want to make changes exclusive to a single component? We then add a bunch of if..else which will then blow out of proportion? 

> The functions also allow us to generate structs that are largely identical save for one field. If we did it with vars/consts we'd have large structs that were largely the same.

But, is it always going to be identical? Is there no possibility that we'd maybe like to configure placement for each component differently (other than the name)?

> Again, why is this not valuable?

It's not "not valuable". It's just not significantly valuable. Here's why I think so

+ it doesn't significantly simplify the code
+ it doesn't make it easier to custom configure each component (we get what the function throws at us)
+ retrieving values would require less cycles then generating values
+ this file is still largely static. The configuration would probably change once in a release or two (functions just feels like an overkill)

I'm not against this re-factor, but I believe it's half way there.
It reduced duplication at the cost of configurability and extra processing cycle.
If it can give me configurability, I'd be more than happy with it. But, that's just me.

Since it's not a very big change, I'm not blocking this with my comment.
I'd like the value add of this refactor to be explained (PR and Commit descriptions) and justified rather than just calling it a "refactor".

2020-10-09 10:53 UTC, umangachapagain commented
> @umangachapagain above is [disscussed here](https://github.com/openshift/ocs-operator/pull/727/files#r485077430) and [here](https://github.com/openshift/ocs-operator/pull/727/files#r485076961)

Can't reach those comments.

2020-10-14 14:07 UTC, jarrpa requested changes
I agree with a number of Umanga's comments. To start, explain in your commit message (and PR description) what this refactor gains us. Specifically, I see it as reducing the complexity of structures that need to be written by hand.

I also agree that this should probably be more configurable to be more meaningful. As such, I'd like you to take any functions that return a list and only return a single element that would go in that list. I've provided an example in a comment below.

2020-10-14 14:07 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +				PreferredDuringSchedulingIgnoredDuringExecution: getWeightedPodAffinityTerm("rook-ceph-mon"),
```suggestion
				PreferredDuringSchedulingIgnoredDuringExecution: []corev1.WeightedPodAffinityTerm{
					getAppWeightedPodAffinityTerm(100, "rook-ceph-mon"),
				}
```

2020-10-14 14:07 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +func getWeightedPodAffinityTerm(selector string) []corev1.WeightedPodAffinityTerm {
```suggestion
func getAppWeightedPodAffinityTerm(weight int, selector string) corev1.WeightedPodAffinityTerm {
```

2020-10-14 14:07 UTC, jarrpa commented on pkg/controller/defaults/placements.go
> +				RequiredDuringSchedulingIgnoredDuringExecution:  getPodAffinityTerm("rook-ceph-rgw"),
```suggestion
				RequiredDuringSchedulingIgnoredDuringExecution:  []corev1.PodAffinityTerm{
					getAppPodAffinityTerm("rook-ceph-rgw"),
				}
```

2020-10-19 09:13 UTC, rajatsing commented
I considered your changes @jarrpa and I think if I start making changes that you suggested, it will make code more complicated and in turn, the whole point of "refactoring" will be of no use.
I think It's better to close it?.
@umangachapagain wdyt?.

2020-10-19 22:07 UTC, jarrpa commented
I completely disagree. Refactoring is more than just simple code. I hate seeing the same exact framework or even exact configuration duplicated in multiple places. While Umanga has a point that these things don't change very frequently (if some would at all), that is no reason to just let the error potential sit around unaddressed. It's all just BZs waiting to come up in QE.

2020-10-20 08:52 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +				PreferredDuringSchedulingIgnoredDuringExecution: getWeightedPodAffinityTerm("rook-ceph-mon"),
added, please check.

2020-10-20 08:52 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +				PreferredDuringSchedulingIgnoredDuringExecution: getWeightedPodAffinityTerm("rook-ceph-mon"),
added, please check!.

2020-10-20 08:53 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +func getWeightedPodAffinityTerm(selector string) []corev1.WeightedPodAffinityTerm {
added, please check!.

2020-10-20 08:53 UTC, rajatsing commented on pkg/controller/defaults/placements.go
> +				RequiredDuringSchedulingIgnoredDuringExecution:  getPodAffinityTerm("rook-ceph-rgw"),
added, please check!.

2020-10-20 08:57 UTC, rajatsing commented
@jarrpa @umangachapagain 
I have added more specific commit and description. Also, based on the suggestion above, I have modified the code in a way that each struct can be modified based on their own individual's value.

2020-10-20 13:19 UTC, jarrpa requested changes
Code looks good, now merge the two commits. :) We don't need to know how you reacted to the review comments in the commit history, just have a clean commit that can be understood (and reverted later if needed).

2020-10-20 13:39 UTC, rajatsing commented
> Code looks good, now merge the two commits. :) We don't need to know how you reacted to the review comments in the commit history, just have a clean commit that can be understood (and reverted later if needed).

Absolutely!. When I was reviewing the code myself, I forgot about to review the older commit sadly. But nvm, I'll squash them and form a new commit.

2020-10-20 13:44 UTC, rajatsing commented
Commit fixed!.

2020-10-20 14:08 UTC, rajatsing commented
I hate it when CI runs on local but fails on remote 👎 .

2020-10-20 18:11 UTC, jarrpa requested changes
One last thing I failed to catch earlier: Instead of taking a `string` and setting it as an element of a `[]string{}`, take `...string` and set it directly as the full list.

2020-10-21 18:27 UTC, jarrpa approved these changes
LGTM, thank you!

2020-10-21 20:33 UTC, merged