Check MCG.Reconcile strategy before deleting Noobaa resources
openshift/ocs-operator pull request #874
Opened 2020-10-28 16:20 UTC by nbalacha

Delete Noobaa resources only they are being managed
by the OCS operator.

Signed-off-by: N Balachandran <nibalach@redhat.com>

2020-10-28 16:20 UTC, nbalacha commented
/assign jarrpa

2020-10-28 16:26 UTC, nbalacha commented
Should the same checks be done for the other Managed resources as well?

2020-10-30 18:31 UTC, jarrpa commented
I think this makes sense thus far.

> Should the same checks be done for the other Managed resources as well?

Now that you mention it, that doesn't sound like a bad idea. @raghavendra-talur or @iamniting do either of you have any thoughts on that?

2020-11-02 05:13 UTC, iamniting requested changes
> I think this makes sense thus far.
> 
> > Should the same checks be done for the other Managed resources as well?
> 
> Now that you mention it, that doesn't sound like a bad idea. @raghavendra-talur or @iamniting do either of you have any thoughts on that?

Make sense to me

2020-11-02 05:13 UTC, iamniting commented on vendor/modules.txt
> +github.com/openshift/api/config/v1
It looks like this Change is not part of this PR

2020-11-02 05:17 UTC, iamniting commented
> Delete Noobaa resources only they are being managed
> by the OCS operator.

@nbalacha I think 'if' is missing here.

Can you pls prefix "StorageCluster:" as we are following that pattern for all our delete or uninstall commits.

[1]. https://github.com/openshift/ocs-operator/blame/fac013610cf1bf1f0f50ae9c7f17d2163e004055/pkg/controller/storagecluster/uninstall_reconciler.go

2020-11-02 06:58 UTC, iamniting requested changes

2020-11-02 06:58 UTC, iamniting commented on deploy/deploy-with-olm.yaml
> +  image: quay.io/nibalach/ocs-registry:master
Same as before

2020-11-02 08:32 UTC, closed without merging