must-gather: collect OBC of all namespaces
openshift/ocs-operator pull request #904
Opened 2020-11-20 12:04 UTC by iamniting

Signed-off-by: Nitin Goyal nigoyal@redhat.com

cc @raghavendra-talur

2020-11-20 12:44 UTC, crombus commented
/hold  because must-gather scope is only in openshift-storage.

@jarrpa can you suggest what to do here.

2020-11-20 14:19 UTC, raghavendra-talur commented
IMO, the exception that was provided for collecting the PVC data in must-gather should also apply for OBC data collection, they belong to the same category.

2020-11-20 14:21 UTC, raghavendra-talur requested changes

2020-11-20 14:21 UTC, raghavendra-talur commented on must-gather/collection-scripts/gather_namespaced_resources
> +# For obc of all namesspaces
s/namesspaces/namespaces

2020-11-20 14:46 UTC, iamniting commented on must-gather/collection-scripts/gather_namespaced_resources
> +# For obc of all namesspaces
Done

2020-11-20 18:58 UTC, raghavendra-talur approved these changes

2020-11-30 15:53 UTC, jarrpa requested changes
I think this is fine, OBCs are analogous to PVCs. However, the second commit should be merged into the first. I also wouldn't mind if a separate commit was added to fix the PVC typo, either in this PR or a separate one.

/hold cancel

2020-12-01 12:04 UTC, iamniting commented
> I think this is fine, OBCs are analogous to PVCs. However, the second commit should be merged into the first. I also wouldn't mind if a separate commit was added to fix the PVC typo, either in this PR or a separate one.
> 
> /hold cancel

Done in this one itsef.

2020-12-01 12:17 UTC, crombus approved these changes

2020-12-01 14:50 UTC, jarrpa approved these changes
/lgtm

2020-12-02 11:15 UTC, merged