Fix Usability Issues in UI caused by the Operator
openshift/ocs-operator pull request #908
Opened 2020-11-23 04:43 UTC by bipuladh

- Removes Monitoring label, consumed by OLM as the namespace will be labelled automatically from the UI during storage cluster creation. (https://bugzilla.redhat.com/show_bug.cgi?id=1866298)
- Adds description annotation for Storage classes.  (https://bugzilla.redhat.com/show_bug.cgi?id=1888548)

2020-11-23 05:35 UTC, umangachapagain approved these changes
I'm not sure how adding Description to Annotations is a UI/UX enhancement. But, it doesn't hurt.

2020-11-23 05:39 UTC, bipuladh commented
> I'm not sure how adding Description to Annotations is a UI/UX enhancement. But, it doesn't hurt.

These descriptions are picked by the UI and displayed in storage class dropdowns.
![Screenshot from 2020-11-03 13-14-49](https://user-images.githubusercontent.com/54092533/99931927-66462600-2d7c-11eb-8045-86b262ecefa0.png)

2020-11-30 08:18 UTC, nbalacha commented
The PR title is misleading. These are changes for UX enhancements, not usability issues with the operator. 
Should the storage class annotations highlight that these are Ceph storage classes? The annotations are generic and do not mention the storage is provided by ceph.

2020-11-30 08:26 UTC, bipuladh commented
> The PR title is misleading. These are changes for UX enhancements, not usability issues with the operator.
> Should the storage class annotations highlight that these are Ceph storage classes? The annotations are generic and do not mention the storage is provided by ceph.

These are usability issues discovered from the Usability Study. The annotations are created as per the recommendation of the UX team.

2020-11-30 08:31 UTC, nbalacha commented
> > The PR title is misleading. These are changes for UX enhancements, not usability issues with the operator.
> > Should the storage class annotations highlight that these are Ceph storage classes? The annotations are generic and do not mention the storage is provided by ceph.
> 
> These are usability issues discovered from the Usability Study. The annotations are created as per the recommendation of the UX team.

These are usability issues in the UX - they are not caused by the operator. This PR adds information to the operator to allow the UI to behave differently. The PR can be reworded to indicate the same.

2020-11-30 17:32 UTC, jarrpa requested changes
I don't like the proposed descriptions. It is meaningless to the user to describe one as a "filesystem" SC and the other as a "block" SC since they can both provide filesystems. The user shouldn't care about the underlying implementation, only what volume and access modes it can provide. I've provided suggestions.

2020-11-30 17:32 UTC, jarrpa commented on pkg/controller/storagecluster/storageclasses.go
> +				"description": "Object storage class",
```suggestion
				"description": "Provides ObjectBucketClaims (OBCs)",
```

2020-11-30 17:32 UTC, jarrpa commented on pkg/controller/storagecluster/storageclasses.go
> +					"description": "File system storage class",
```suggestion
					"description": "Provides RWO and RWX Filesystem volumes",
```

2020-11-30 17:32 UTC, jarrpa commented on pkg/controller/storagecluster/storageclasses.go
> +					"description": "Block storage class",
```suggestion
					"description": "Provides RWO Filesystem volumes, and RWO and RWX Block volumes",
```

2020-12-03 13:31 UTC, bipuladh commented
> I don't like the proposed descriptions. It is meaningless to the user to describe one as a "filesystem" SC and the other as a "block" SC since they can both provide filesystems. The user shouldn't care about the underlying implementation, only what volume and access modes it can provide. I've provided suggestions.

Thanks for the suggestions, I asked the UX folks to have a look at it, and they agree with it, moving forward with your suggestions.

2020-12-03 17:23 UTC, jarrpa commented on pkg/controller/storagecluster/storageclasses.go
> +const (
This change is unrelated and being taken care of in another PR, please remove it.

2020-12-07 11:51 UTC, nbalacha approved these changes

2020-12-07 16:42 UTC, jarrpa approved these changes
/lgtm

2020-12-07 16:43 UTC, jarrpa commented
/test ocs-operator-ci

2020-12-07 16:43 UTC, jarrpa commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws

2020-12-07 18:25 UTC, merged