CSV generator for OCS on OSD
openshift/ocs-operator pull request #930
Opened 2020-12-02 15:13 UTC by umangachapagain

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

2020-12-02 16:17 UTC, obnoxxx commented
@umangachapagain - can you provide some context in the PR message?

2020-12-02 16:56 UTC, jarrpa commented
> @umangachapagain - can you provide some context in the PR message?

Indeed. Please explain what OSD is and what the deployer does.

2020-12-03 15:43 UTC, umangachapagain commented
@nb-ohad Please review and verify the PR description. I've added what I understood (and it may not be correct)

@obnoxxx @jarrpa PTAL.

2020-12-03 16:30 UTC, nb-ohad commented
@umangachapagain Can we change all OSD references to OSD deployer?
for example, instead of `LATEST_OSD_IMAGE` let`s do `LATEST_OSD_DEPLOYER_IMAGE` 
and instead of `gen-osd` let's do `gen-osd-deployer-csv`.

I think it will help in minimizing the confusion.

2020-12-03 16:32 UTC, nb-ohad commented
Also regarding the usage I would prefer a new make target, so instead of `GEN_OSD=true make gen-latest-csv` we will do `make `get-latest-csv-for-osd` or `get-latest-csv-for-openshift-dedicated` if we want to be more explicit, but i think the name si to long.

2020-12-03 17:29 UTC, jarrpa commented
I like the PR description, now please also add it in the commit message.

2020-12-08 08:56 UTC, iamniting requested changes

2020-12-08 08:56 UTC, iamniting commented on tools/csv-merger/csv-merger.go
> +						Name:            "deployer",
I would suggest the pod name should be the same as the deployment name.

2020-12-10 10:25 UTC, obnoxxx commented
/hold

I am just putting a protective hold on this as there is a discussion going whether to put the csv generation somewhere else.
This doesn't prevent us from continuing on this PR and getting it into shape.

2021-01-13 17:48 UTC, jarrpa commented
I don't think this is valid anymore? Is it?

2021-01-13 19:27 UTC, nb-ohad commented
It should be with some changes

2021-03-17 06:01 UTC, umangachapagain commented
This is not required as a better alternative was found.

2021-03-17 06:01 UTC, closed without merging