Source Manifest uses template instead of OCS_IMAGE for backward compatibility
openshift/ocs-operator pull request #973
Opened 2020-12-25 03:28 UTC by umangachapagain

Before migrating to new project structure and tools, CSV Merger was using templates added by source-manifests to inject OCS_IMAGE value. When we moved to using Kustomize, we set the images directly instead of first templating and replacing.
This broke the build pipeline as it didn't safeguard itself against uninitialized OCS_IMAGE var.

This PR reverts back to using templates instead of Kustomize to unblock the build pipeline.
Alternatively, build pipeline can set OCS_IMAGE env var a little early and all will be well (without this PR)

2020-12-25 08:31 UTC, obnoxxx requested changes

2020-12-25 08:31 UTC, obnoxxx commented on hack/source-manifests.sh
> +		cp config/crd/bases/* $ocs_crds_outdir
unintended indentation?

```suggestion
	cp config/crd/bases/* $ocs_crds_outdir
```

2020-12-25 08:36 UTC, umangachapagain commented on hack/source-manifests.sh
> +		cp config/crd/bases/* $ocs_crds_outdir
yes, fixed.

2021-01-04 15:12 UTC, umangachapagain commented
Build pipeline is fixed. Closing this PR as we decided to use Kustomize instead of Go Templates for simplicity.

2021-01-04 15:12 UTC, closed without merging