fix misspelling across codebase
openshift/ocs-operator pull request #993
Opened 2021-01-15 13:30 UTC by umangachapagain

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

2021-01-18 23:11 UTC, obnoxxx requested changes
Good catches, but I think there's still one error. See inline.

2021-01-18 23:11 UTC, obnoxxx commented on controllers/util/predicates.go
> +// ComposePredicates will compose a variable number of predicate and return a predicate that
```suggestion
// ComposePredicates will compose a variable number of predicates and return a predicate that
```

2021-01-21 07:48 UTC, umangachapagain commented
> Good catches, but I think there's still one error. See inline.

Gotta catch 'em all.

2021-01-21 09:27 UTC, obnoxxx approved these changes
/lgtm

2021-01-21 09:27 UTC, obnoxxx commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws

2021-01-21 09:32 UTC, merged